import { Injectable } from '@angular/core';
import { er } from '@fullcalendar/core/internal-common';

@Injectable({
  providedIn: 'root'
})
export class DataTextService {
  private language = 'pt-BR'; // Default language
  public texts: any;

  constructor() {
    this.init();
  }

  async init() {
   
    const storedLanguage = 'pt-BR';
    this.language = storedLanguage || this.language;
    this.setLanguage(this.language);
  }

  async setLanguage(language: string) {
    this.language = language;
    
    this.texts = this.getTextsForLanguage(language);
  }

  private getTextsForLanguage(language: string) {
    const languages = {
      'en': {
      attention: 'Attention',
      success: 'Success',
      errorLogin: 'Error logging in. Please try again.',
      errorLogin1: 'Could not retrieve user data. Please check your information.',
      errorLogin2: 'User type mismatch. Contact support.',
      errorLogin3: 'Your account has been removed. Please contact support.',
      errorLogin4: 'Your account is inactive. Please contact support.',
      errorLogin5: 'Profile information incomplete. Please complete your profile.',
      warning: 'Warning',
      yes: 'Yes',
      no: 'No',
      pleaseWait: 'Please wait...',
      titleUsernameMinLength: 'Username must be at least 6 characters.',
      titlePasswordMinLength: 'Password must be at least 6 characters.',
      titleCheckMailbox: 'Check your email for further instructions.',
      titleAuthRecoveryError: 'Could not send recovery email.',
      cancel: 'Cancel',
      titleStatusNotVerified: 'Not Verified',
      titleStatusVerified: 'Verified',
      titleRankingBronze: 'Bronze',
      titleCreated: 'Created',
      titleAccept: 'Accept',
      successPasswordReset: 'Password reset email sent successfully.',
      invalid_field: 'Invalid field',
      documents: 'Documentation',
      requests: 'Requests',
      runs: 'Jobs',
      reports: 'Reports',
      dateRequest: 'Request date',
      moreInformation: 'More information',
      dropPoints: 'Job information',
      dropPointsDispute: 'Dispute information',
      winner: 'Winner',
      region: 'Area',
      msgIsDemo: 'Thank you for your interest in the pedmoto App! This is a demo application for prospective clients. Contact us at (61) 98301-3768 or admin@dbltecnologia.com.br.',
      dataRequestAccepted: 'Request accepted on',
      cancelRequest: 'Cancel request',
      requestAgain: 'Request again',
      date: 'Date',
      dateStart: 'Start date',
      dateEnd: 'End date',
      datetimeEnd: 'End time',
      search: 'Search',
      received: 'Received',
      titleChangeValue: 'Modify',
      download: 'Download',
      professional: 'Professional',
      client: 'Client',
      dataArrived: 'Arrival date',
      dataEnd: 'End date',
      collectPoint: 'Collection point',
      delivery: 'Delivery',
      estimatedTime: 'Estimated time',
      totalWait: 'Wait time',
      totalWaitCharged: 'Charged time',
      totalTimeWaitingFree: 'Tolerance time',
      minutes: 'Minutes',
      duration: 'Duration',
      distance: 'Distance',
      totalDuration: 'Total duration',
      totalDistance: 'Total distance of deliveries',
      totalDistanceReturn: 'Return distance',
      totalDistanceAll: 'Total final distance',
      totalDistanceNotifications: 'Notification distance',
      details: 'Details',
      totalWaitValue: 'Wait time value',
      totalValueRun: 'Job value',
      paymentMethod: 'Payment method',
      changeFor: 'Change for',
      msgCanceled: 'Cancellation message',
      msgFinish: 'Completion message',
      responsible: 'Responsible',
      instructions: 'Instructions',
      charge: 'Charge',
      arrived: 'Arrived',
      signedBy: 'Signed by',
      attachment: 'Attachment',
      expand: 'Expand',
      tablePrice: 'Price table',
      retrain: 'Retrain',
      check: 'Verify',
      checkout: 'Checkout',
      qualify: 'Rate',
      datetimeReport: 'Report requested at',
      open: 'Open',
      yourEmail: 'Your email',
      phoneNumber: 'Phone number',
      yourPassword: 'Your password',
      state: 'State',
      login: 'Login',
      newUser: 'New user?',
      send: 'Send',
      createNewAccount: 'Create new account',
      register: 'Sign up',
      forgotPass: 'Forgot password',
      informYourEmail: 'Enter your email',
      professionalName: 'Professional name',
      calculating: 'Calculating...',
      workSentSuccess: 'Service sent successfully. You will be notified once accepted.',
      selectTheService: 'Select the desired service and double-click to confirm.',
      errorInput: 'Please provide a valid address.',
      errorInputTo: 'Please provide the destination address.',
      enterSmsCodeHeader: 'Enter the code',
      smsCodePlaceholder: 'Code',
      waiting: 'Waiting',
      ratingModalMessage: 'Your feedback is important to us. Rating the service helps improve our platform and builds trust within the community.',
      },
      'pt-BR': {
        attention: 'Atenção',
        success: 'Sucesso',
        errorLogin: 'Erro ao entrar. Por favor, tente novamente.',
        errorLogin1: 'Não foi possível obter os dados do usuário. Verifique suas informações.',
        errorLogin2: 'Tipo de usuário incorreto. Entre em contato com o suporte.',
        errorLogin3: 'Sua conta foi removida. Por favor, entre em contato com o suporte.',
        errorLogin4: 'Sua conta está inativa. Por favor, entre em contato com o suporte.',
        errorLogin5: 'Informações do perfil incompletas. Complete seu perfil.',
        warning: 'Aviso',
        yes: 'Sim',
        no: 'Não',
        
        titleUsernameMinLength: 'O nome de usuário deve ter pelo menos 6 caracteres.',
        titlePasswordMinLength: 'A senha deve ter pelo menos 6 caracteres.',
        titleCheckMailbox: 'Verifique seu e-mail para mais instruções.',
        titleAuthRecoveryError: 'Não foi possível enviar o e-mail de recuperação.',
        cancel: 'Cancelar',
        send: 'Enviar',
        titleStatusNotVerified: 'Não Verificado',
        titleStatusVerified: 'Verificado',
        titleRankingBronze: 'Bronze',
        titleCreated: 'Criado',
        titleAccept: 'Aceitar',
        successPasswordReset: 'E-mail de redefinição de senha enviado com sucesso.',
        invalid_field: 'Campo inválido',
        documents: 'Documentação',
        requests: 'Solicitações',
        runs: 'Corridas',
        reports: 'Relatórios',
        dateRequest: 'Data da solicitação',
        moreInformation: 'Mais informações',
        dropPoints: 'Informações da corrida',
        dropPointsDispute: 'Informações da disputa',
        winner: 'Vencedor',
        region: 'Região',
        msgIsDemo: 'Muito obrigado pelo seu interesse no Pedmoto! Este é um aplicativo de demonstração para potenciais clientes. Contate-nos pelo (61) 98301-3768 ou admin@dbltecnologia.com.br.',
        dataRequestAccepted: 'Data de aceite',
        cancelRequest: 'Cancelar solicitação',
        requestAgain: 'Solicitar novamente',
        dateStart: 'Data inicial',
        dateEnd: 'Data final',
        datetimeEnd: 'Horário de término',
        search: 'Procurar',
        received: 'Recebido',
        titleChangeValue: 'Modificar',
        download: 'Download',
        professional: 'Profissional',
        client: 'Cliente',
        dataArrived: 'Data de chegada',
        dataEnd: 'Data de término',
        collectPoint: 'Ponto de coleta',
        delivery: 'Entrega',
        estimatedTime: 'Tempo estimado',
        totalWait: 'Tempo de espera',
        totalWaitCharged: 'Tempo cobrado',
        totalTimeWaitingFree: 'Tempo de tolerância',
        minutes: 'Minutos',
        duration: 'Duração',
        distance: 'Distância',
        totalDuration: 'Duração',
        totalDistance: 'Dist.',
        totalDistanceReturn: 'Distância de retorno',
        totalDistanceAll: 'Distância total final',
        totalDistanceNotifications: 'Distância para notificações',
        details: 'Detalhes',
        totalWaitValue: 'Valor do tempo de espera',
        totalValueRun: 'Valor da corrida',
        paymentMethod: 'Método de pagamento',
        changeFor: 'Troco para',
        msgCanceled: 'Mensagem de cancelamento',
        msgFinish: 'Mensagem de finalização',
        responsible: 'Responsável',
        instructions: 'Instruções',
        charge: 'Cobrar',
        arrived: 'Chegou',
        signedBy: 'Assinado por',
        attachment: 'Anexo',
        expand: 'Expandir',
        tablePrice: 'Tabela de preços',
        retrain: 'Reduzir',
        check: 'Verificar',
        checkout: 'Finalizar',
        qualify: 'Qualificar',
        datetimeReport: 'Relatório solicitado às',
        open: 'Abrir',
        yourEmail: 'Seu e-mail',
        phoneNumber: 'Número de telefone',
        yourPassword: 'Sua senha',
        state: 'Estado',
        login: 'Entrar',
        newUser: 'Novo usuário?',
        createNewAccount: 'Criar nova conta',
        register: 'Cadastrar',
        forgotPass: 'Esqueceu a senha',
        informYourEmail: 'Informe seu e-mail',
        professionalName: 'Nome do profissional',
        calculating: 'Calculando...',
        workSentSuccess: 'Serviço enviado com sucesso. Você será notificado ao ser aceito.',
        selectTheService: 'Selecione o serviço desejado e clique duas vezes para confirmar.',
        errorInput: 'Forneça um endereço válido.',
        errorInputTo: 'Forneça o endereço de destino.',
        enterSmsCodeHeader: 'Código de verificação',
        smsCodePlaceholder: 'Código',
        titleName: 'Nome',
        titleEmail: 'E-mail',
        titlePhone: 'Telefone',
        titleService: 'Serviço',
        titleDate: 'Data',
        titleYourPhonePlaceHolder: 'Telefone',
        titleYourPasswordPlaceHolder: 'Senha',
        titleYourPasswordConfirmPlaceHolder: 'Confirme a senha',        
        passwordNotMatch: 'As senhas não coincidem',
        addClient: 'Adicionar cliente',
        addProfessional: 'Adicionar profissional',
        termsUse: 'Termos de uso',
        privacy: 'Política de privacidade',
        goTerms: 'Ir para os termos de uso',
        goPriv: 'Ir para a política de privacidade',
        emailInUseHeader: 'E-mail já em uso',
        emailInUseMessage: 'O e-mail já está em uso. Por favor, escolha outro.',
        pickUp: 'Pegar',
        dropOff: 'Largar',
        pickUpPlaceholder: 'Endereço de retirada',
        dropOffPlaceholder: 'Endereço de entrega',
        additionalDestination: 'Destino adicional',
        addDestination: 'Adicionar destino',
        originLabel: 'Origem',  
        destinationLabel: 'Destino',
        originPlaceholder: 'Endereço de retirada',
        destinationPlaceholder: 'Endereço de entrega',
        additionalDestinationPlaceholder: 'Endereço de destino adicional',
        waiting: 'Aguardando',
        textRequest: 'Solicitação',
        appCurrency: 'R$',
        organize: 'Organizar',
        textCalc: 'Calcular',
        next: 'Próximo',
        textRestore: 'Restaurar',
        addToAddress: 'Adicionar ao endereço',
        titleResume: 'Resumo',
        textEstimatedDistance: 'Distância estimada',
        machine: 'Máquina',
        pix: 'PIX',
        cash: 'Dinheiro',
        cashChangePlaceholder: 'Troco para',
        addInfo: 'Adicionar informações',
        payment: 'Forma de pagamento',
        reference: 'Referência',        
        finalPassword: 'Senha final',
        address: 'Endereço',
        addAddress: 'Adicionar endereço',
        returnPoint: 'Retorno',
        cashChange: 'Troco',
        password: 'Senha',
        enterAddress: 'Digite o endereço',
        options: 'Opções',
        clear: 'Limpar',
        titleMinPoints: 'Você deve ter no mínimo 2 pontos.',
        summary: 'Resumo dos Dados',        
        totalPoints: 'Pontos',
        initialValue: 'Valor Inicial',
        valuePerMeter: 'Valor por Metragem',
        valuePerPoint: 'Valor por Ponto',
        finalPrice: 'Preço Final',
        recalculate: 'Recalcular',
        valueStart: 'Valor Inicial',
        valueMeter: 'Valor por Metragem',
        workFreePoints: 'Pontos Gratuitos',
        calculatedPrice: 'Preço Calculado',
        distanceCharged: 'Distância',
        prices: 'Preços',
        selectTable: 'Selecione a tabela',
        selectOption: 'Selecione a opção',
        tableDetails: 'Detalhes da Tabela',
        priceTable: 'Tabela de Preços',
        price: 'Preço',
        pleaseWait: 'Por favor, aguarde...',
        distanceFromStart: 'Distância da Coleta',
        erorLogin1: 'Não foi possível obter os dados do usuário. Verifique suas informações.',
        erorLogin2: 'Tipo de usuário incorreto. Entre em contato com o suporte.',
        erorLogin3: 'Sua conta foi removida. Por favor, entre em contato com o suporte.',
        timeFromStart: 'Tempo da Coleta',
        collect: 'Coleta',
        timeToNext: 'Tempo para o Próximo',
        explanation: 'Explicação',
        totalTime: 'Tempo',
        calculationDetails: 'Detalhes',
        confirm: 'Confirmar',
        loading: 'Carregando...',
        orderCompleted: 'Sua ordem foi concluída com sucesso.',
        orderSaveError: 'Erro ao salvar a ordem no histórico.',
        completeOrder: 'Concluir a ordem',
        cancelOrder: 'Cancelar a ordem',
        arrivedAt: 'Chegou em',
        remove: 'Remover',
        save: 'Salvar',
        notifyingDrivers: 'Notificando entregadores',        
        clearFields: 'Limpar Campos',
        centerMap: 'Centralizar Mapa',
        exportExcel: 'Exportar para Excel',
        exportPDF: 'Exportar para PDF',
        history: 'Histórico',
        filter: 'Filtrar',
        startDate: 'Data de Início',
        endDate: 'Data de Término',
        applyFilter: 'Aplicar Filtro',
        export: 'Exportar',
        orderHistory: 'Histórico de Ordens',
        status: 'Status',
        createdAt: 'Data de Criação',
        time: 'Tempo',
        accepted: 'Aceito',
        completed: 'Concluído',
        canceled: 'Cancelado',
        all: 'Todos',
        driverDashboard: 'Pedmoto',
        overview: 'Visão Geral',
        availableServices: 'Serviços Disponíveis',
        servicesCompleted: 'Serviços Concluídos',
        walletBalance: 'Saldo',
        wallet: 'Carteira',
        totalServices: 'Serviços',
        orderValue: 'Valor do Pedido',
        driverEarnings: 'Ganhos do Entregador',
        driver: 'Entregador(a)',
        distanceToPickup: 'Distância para Coleta',
        estimatedTimeToPickup: 'Tempo Estimado para Coleta',
        viewDetails: 'Detalhes',
        hideDetails: 'Esconder Detalhes',
        noServicesAvailable: 'Nenhum serviço disponível no momento.',        
        totalClients: 'Clientes',
        onlineDrivers: 'Online',
        refresh: 'Atualizar',
        earningsToday: 'Ganhos Hoje',
        earningsThisMonth: 'Ganhos Este Mês',
        support: 'Suporte',
        service: 'Serviço',
        userProfile: 'Perfil do Usuário',
        accept: 'Aceitar',
        rating: 'Avaliação',
        requestWithdrawal: 'Solicitar Saque',
        withdrawalRules: 'Regras de Saque',
        withdrawalHistory: 'Histórico de Saques',
        confirmWithdrawal: 'Confirmar Saque',
        withdrawal: 'Saque',
        value: 'Valor',
        buyToken: 'Comprar Token',
        processingWithdrawal: 'Processando saque...',
        finished: 'Finalizado',
        processing: 'Processando',
        pending: 'Pendente',
        amount: 'Valor',
        invalidWithdrawalAmount: 'Valor de saque inválido.',
        ratingModalMessage: 'Sua avaliação é importante para nós. Avaliar o serviço ajuda a melhorar nossa plataforma e cria confiança na comunidade.',
        confirmCancelOrder: 'Deseja realmente cancelar o pedido?',
        confirmCancelOrderMessage: 'Ao cancelar o pedido, ele será removido da lista de serviços disponíveis.',
        selectRating: 'Selecione a avaliação',
        addComment: 'Adicione um comentário',
        saveRating: 'Salvar Avaliação',
        confirmRatingMessage: 'Deseja realmente enviar a avaliação?',
        alreadyRated: 'Você já avaliou este serviço',
        documentExplanationTitle: 'Envie sua Documentação',
        documentExplanationDetails: 'Para garantir a segurança da plataforma, é necessário enviar seus documentos para verificação. Mais documentos aumentam suas chances de receber melhores oportunidades.',
        uploadDocuments: 'Documentação',
        documentDetails: 'Selecione e envie os documentos necessários.',
        moreDocumentsBetter: 'Quanto mais documentos você enviar, maior será a sua credibilidade.',
        viewUploaded: 'Ver Enviados',
        uploadingDocument: "Enviando documento...",
        contactSupport: 'Contate o suporte',
        upload: 'Enviar',
        date: 'Data',
        addresses: 'Endereços',
        systemFee: 'Taxa do Sistema',
        fixedFee: 'Taxa Fixa',
        currentStatusNotWaiting: 'Você só pode cancelar o chamado se ele não foi ainda aceito'
              
        
      }
    };

    return languages[language] || languages['pt-BR']; // Default to pt-BR
  }

  getText(key: string): string {
    return this.texts[key] || key;
  }
}
